### ISSUE TITLE
"Maven descriptor missing in Ceylon module" with plugin versiono 1.3.2

### ISSUE THREAD

**Issue by albx79** [vietj/ceylon-maven-plugin#16] opened 2017-06-02 14:18 UTC
I'm compiling the example project https://github.com/vietj/ceylon-maven-example

If I set the plugin version to 1.3.2, mvn compile fails with the following error:
[ERROR] Failed to execute goal org.ceylon-lang:ceylon-maven-plugin:1.3.2:compile (default) on project ceylon-maven-example: Maven descriptor missing in Ceylon module /home/dev/alberto/ceylon-maven-example/target/modules/com/acme/foo/1.0.0/com.acme.foo-1.0.0.car: perhaps you did not set group/artifact to com.acme:ceylon-maven-example? -> [Help 1]

Version 1.3.1 works fine.

This is my `mvn --version`:
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-78-generic", arch: "amd64", family: "unix"

**Comment by FroMage** [comment] 2017-06-02 14:35
I submitted a PR at https://github.com/vietj/ceylon-maven-example/pull/2 to update the example code. Closing this since it's not really a bug.

Thanks for the heads-up!

**Closed as completed by FroMage** 2017-06-02 14:35 UTC

**Comment by rtvd** [comment] 2018-03-10 10:46
I am a bit puzzled.
So how should the code / pom be changed to make it work with plugin of version 1.3.2 or 1.3.3?

My pom.xml looks like this now and I still see an error:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>com.acme</groupId>
  <artifactId>ceylon-maven-example</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <dependencies>
        <dependency>
                <groupId>org.ceylon-lang</groupId>
                <artifactId>ceylon.language</artifactId>
                <version>1.3.3</version>
        </dependency>
  </dependencies>

  <build>

    <plugins>

      <plugin>
        <groupId>org.ceylon-lang</groupId>
        <artifactId>ceylon-maven-plugin</artifactId>
        <version>1.3.3</version>
        <configuration>
          <module>com.acme.foo/1.0.0</module>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

    </plugins>
  </build>

</project>
```

**Comment by FroMage** [comment] 2018-03-10 11:19
What's your error?

**Comment by rtvd** [comment] 2018-03-10 11:26
```
$ mvn compile
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ceylon-maven-example 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ ceylon-maven-example ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /usr/local/PRIVATE/src/ALIEN/ceylon-maven-example/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ ceylon-maven-example ---
[INFO] No sources to compile
[INFO] 
[INFO] --- ceylon-maven-plugin:1.3.3:compile (default) @ ceylon-maven-example ---
[INFO] Compiled module com.acme.foo/1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.373 s
[INFO] Finished at: 2018-03-10T10:40:23+00:00
[INFO] Final Memory: 33M/504M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.ceylon-lang:ceylon-maven-plugin:1.3.3:compile (default) on project ceylon-maven-example: Maven descriptor missing in Ceylon module /usr/local/PRIVATE/src/ALIEN/ceylon-maven-example/target/modules/com/acme/foo/1.0.0/com.acme.foo-1.0.0.car: perhaps you did not set group/artifact to com.acme:ceylon-maven-example? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by FroMage** [comment] 2018-03-10 11:28
And what does your module descriptor look like?

**Comment by rtvd** [comment] 2018-03-10 11:31
src/main/ceylon/com/acme/foo/module.ceylon?

```
module com.acme.foo "1.0.0" {

}
```

Basically I did "git clone" for this project today, confirmed that it can be compiled and then tried changing the version to 1.3.3.

**Comment by FroMage** [comment] 2018-03-10 11:33
Apparently my PR was not merged. You need this descriptor:

```
native("jvm")
module com.acme.foo maven:com.acme:"ceylon-maven-example" "1.0.0" {
}
```

**Comment by rtvd** [comment] 2018-03-10 11:34
Ah.. That finally works.
Thank you very much!

Is it because of some new changes in Ceylon 1.3.x?

**Comment by quintesse** [comment] 2018-03-10 13:14
@FroMage isn't it confusing to have different names for the ceylon module and the Maven artifact?

**Comment by FroMage** [comment] 2018-03-12 08:27
> Is it because of some new changes in Ceylon 1.3.x?

And changes in the maven plugin so that it checks things for consistency.

**Comment by FroMage** [comment] 2018-03-12 08:27
> @FroMage isn't it confusing to have different names for the ceylon module and the Maven artifact?

Well, yes and no. It helps illustrate that the names can be complex.
